"""
StormPulse V2 — Weighted T1/T2/T3 Confidence Scoring
====================================================

Single source of truth for how every object StormPulse serves (alert, LSR,
corridor) is assigned a confidence tier, and how corridor confidence *strength*
(HIGH / MEDIUM / LOW) is computed.

The model has two independent, deterministic parts:

1. TIER ASSIGNMENT (provenance — "who asserts this claim?")
   Each object is described by the set of evidence signals backing its claim.
   Each signal has a named weight. The tier score is the weight of the
   *dominant* (highest-weighted) signal present — accumulation of weak signals
   can never masquerade as official confirmation. Fixed thresholds map the
   score to a tier:

       score >= T1_THRESHOLD (0.85)  -> T1  Officially Confirmed
       score >= T2_THRESHOLD (0.40)  -> T2  Official Near-Real-Time
       otherwise                     -> T3  System-Inferred

   IMPORTANT: we tier the *claim*, not its ingredients. A system-generated
   corridor polygon is a claim asserted only by our model, so its signal set
   is {INFERRED_GEOMETRY} (=> T3) even though the LSRs that fed it are T1/T2
   objects in their own right. A flood-zone corridor that re-serves an
   official NWS warning polygon verbatim carries OFFICIAL_WARNING_PRODUCT
   (=> T2) because the geometry itself is an official product.

2. CORRIDOR CONFIDENCE STRENGTH (evidence quality — "how good is the track?")
   A weighted additive model over report counts, official-warning backing,
   and Corridor Engine v2 motion-quality metrics, capped at 1.0 and labeled
   HIGH / MEDIUM / LOW. This is orthogonal to the tier: a T3 corridor can be
   HIGH confidence (dense, linear, warned track) yet remains T3 because no
   official source asserts the swath.

Full methodology, worked examples, and validation results:
docs/CONFIDENCE_SCORING.md. Validation harness: scripts/validate_scoring.py.

Everything in this module is pure and deterministic: same inputs, same tier,
same score — no clock reads, no randomness, no I/O.
"""
from dataclasses import dataclass
from enum import Enum
from typing import Iterable, Optional, Tuple


# ─────────────────────────────────────────────────────────────────────────────
# Part 1 — Tier assignment (provenance model)
# ─────────────────────────────────────────────────────────────────────────────

class Signal(str, Enum):
    """Evidence signals that can back a claim served by StormPulse."""

    NWS_DAMAGE_SURVEY = "NWS_DAMAGE_SURVEY"
    """Official post-event NWS damage survey (DAT / Public Information
    Statement). The strongest possible confirmation."""

    CONFIRMED_TORNADO_LSR = "CONFIRMED_TORNADO_LSR"
    """NWS/SPC Local Storm Report of a tornado (type codes T/TF/TW) from a
    trained spotter, emergency manager, or law enforcement."""

    OFFICIAL_WARNING_PRODUCT = "OFFICIAL_WARNING_PRODUCT"
    """Active NWS Warning or Emergency product (radar-indicated or observed):
    Tornado Warning, Severe Thunderstorm Warning, Flash Flood Warning, etc.
    Official and near-real-time, but not ground-truth confirmation."""

    OFFICIAL_WATCH_OR_ADVISORY = "OFFICIAL_WATCH_OR_ADVISORY"
    """Active NWS Watch, Advisory, or Statement product. Official situational
    awareness — lower certainty than a Warning."""

    UNCONFIRMED_LSR = "UNCONFIRMED_LSR"
    """Near-real-time storm report that is not a confirmed tornado report:
    wind damage, hail, dust storm, etc. Official channel, unverified content."""

    INFERRED_GEOMETRY = "INFERRED_GEOMETRY"
    """Geometry or claim generated by the StormPulse Corridor Engine. No
    official source asserts it. Always carries a disclaimer."""


#: Named weight per signal. Weights encode *authoritativeness of the source
#: asserting the claim*, on a 0–1 scale. Tuned against the 20-event historical
#: fixture set (scripts/fixtures/historical_events.json) — see
#: docs/CONFIDENCE_SCORING.md for the rationale behind each value.
SIGNAL_WEIGHTS: dict[Signal, float] = {
    Signal.NWS_DAMAGE_SURVEY:          1.00,
    Signal.CONFIRMED_TORNADO_LSR:      0.90,
    Signal.OFFICIAL_WARNING_PRODUCT:   0.60,
    Signal.OFFICIAL_WATCH_OR_ADVISORY: 0.50,
    Signal.UNCONFIRMED_LSR:            0.45,
    Signal.INFERRED_GEOMETRY:          0.20,
}

#: Dominant-signal score at or above this ⇒ T1 (Officially Confirmed).
T1_THRESHOLD = 0.85
#: Dominant-signal score at or above this (and below T1) ⇒ T2 (Official
#: Near-Real-Time). Below ⇒ T3 (System-Inferred).
T2_THRESHOLD = 0.40

TIER_LABELS = {
    "T1": "Official Confirmed",
    "T2": "Official Near-Real-Time",
    "T3": "Inferred (System Generated)",
}

#: Disclaimer text attached to every T3 (inferred) payload, verbatim, in both
#: the API response and the UI.
T3_DISCLAIMER = (
    "INFERRED LAYER - System-generated estimate. "
    "Not an official NWS damage survey or warning product."
)


@dataclass(frozen=True)
class TierResult:
    """Outcome of tier assignment. Immutable and comparable for tests."""
    tier: str                          # "T1" | "T2" | "T3"
    score: float                       # weight of the dominant signal
    dominant_signal: Optional[Signal]  # None only for an empty signal set
    rationale: str                     # human-readable one-liner

    @property
    def label(self) -> str:
        return TIER_LABELS[self.tier]


def assign_tier(signals: Iterable[Signal]) -> TierResult:
    """
    Assign a T1/T2/T3 tier from the evidence signals backing a claim.

    Deterministic dominant-signal model: the tier score is the maximum weight
    among the signals present. An empty signal set degrades to T3 with score
    0.0 (nothing asserts the claim).
    """
    present = set(signals)
    if not present:
        return TierResult("T3", 0.0, None, "No backing signals — inferred by default.")

    dominant = max(present, key=lambda s: SIGNAL_WEIGHTS[s])
    score = SIGNAL_WEIGHTS[dominant]

    if score >= T1_THRESHOLD:
        tier = "T1"
    elif score >= T2_THRESHOLD:
        tier = "T2"
    else:
        tier = "T3"

    rationale = (
        f"Dominant signal {dominant.value} (weight {score:.2f}) "
        f"=> {tier} ({TIER_LABELS[tier]})"
    )
    return TierResult(tier, score, dominant, rationale)


# ── Domain adapters: map raw ingested objects to signal sets ─────────────────

#: LSR type codes that count as a confirmed tornado report.
TORNADO_LSR_CODES = {"T", "TF", "TW"}


def tier_for_alert(event_type: str) -> TierResult:
    """
    Tier for an active NWS alert product.

    All alert products are official near-real-time information (T2): a Warning
    is radar-indicated or spotter-relayed, not a completed damage confirmation,
    and a Watch/Advisory is even less certain. Neither reaches T1 — only a
    damage survey or confirmed tornado LSR does.
    """
    et = event_type or ""
    if "Warning" in et or "Emergency" in et:
        return assign_tier({Signal.OFFICIAL_WARNING_PRODUCT})
    return assign_tier({Signal.OFFICIAL_WATCH_OR_ADVISORY})


def tier_for_lsr(type_code: str) -> TierResult:
    """
    Tier for a Local Storm Report.

    Tornado reports (T/TF/TW) come from trained spotters / emergency managers
    and are treated as officially confirmed ground truth (T1). All other
    report types (wind, hail, ...) are official but unverified (T2).
    """
    if (type_code or "").upper() in TORNADO_LSR_CODES:
        return assign_tier({Signal.CONFIRMED_TORNADO_LSR})
    return assign_tier({Signal.UNCONFIRMED_LSR})


def tier_for_corridor(is_official_geometry: bool) -> TierResult:
    """
    Tier for a corridor polygon.

    Engine-generated corridors are inferred claims (T3) regardless of how many
    T1/T2 reports fed them — see the module docstring ("tier the claim, not
    the ingredients"). Flood-zone corridors that re-serve an official NWS
    warning polygon verbatim are official products (T2).
    """
    if is_official_geometry:
        return assign_tier({Signal.OFFICIAL_WARNING_PRODUCT})
    return assign_tier({Signal.INFERRED_GEOMETRY})


# ─────────────────────────────────────────────────────────────────────────────
# Part 2 — Corridor confidence strength (HIGH / MEDIUM / LOW)
# ─────────────────────────────────────────────────────────────────────────────
# Weighted additive model, capped at 1.0. Every weight and threshold is named
# here so the model is reproducible from this file alone.

# Report-count evidence (capped so one mega-outbreak can't saturate a corridor)
W_TORNADO_REPORT = 0.18     #: per confirmed tornado report in the chain
CAP_TORNADO_REPORTS = 0.45  #: max contribution from tornado reports
W_WIND_REPORT = 0.04        #: per wind-damage report in the chain
CAP_WIND_REPORTS = 0.12     #: max contribution from wind reports

# Official backing
W_ACTIVE_WARNING = 0.15     #: an active NWS warning covers the chain's area

# Corridor Engine v2 motion-quality bonuses
CONSISTENCY_HIGH = 0.85     #: circular-R at/above ⇒ nearly perfectly linear track
CONSISTENCY_MED = 0.65
CONSISTENCY_LOW = 0.40
W_CONSISTENCY_HIGH = 0.18
W_CONSISTENCY_MED = 0.10
W_CONSISTENCY_LOW = 0.04

INLIER_HIGH = 0.90          #: fraction of reports fitting the motion model
INLIER_MED = 0.70
W_INLIER_HIGH = 0.08
W_INLIER_MED = 0.04

# Wind / severe corridor weights
W_WIND_CORRIDOR_REPORT = 0.15
CAP_WIND_CORRIDOR = 0.60
W_WIND_CORRIDOR_WARNING = 0.25
W_SEVERE_CORRIDOR_REPORT = 0.10
CAP_SEVERE_CORRIDOR = 0.50
W_SEVERE_CORRIDOR_WARNING = 0.30

# Label thresholds (shared by all corridor categories)
LABEL_HIGH_THRESHOLD = 0.70
LABEL_MEDIUM_THRESHOLD = 0.40


def _label(score: float) -> Tuple[float, str]:
    if score >= LABEL_HIGH_THRESHOLD:
        return score, "HIGH"
    elif score >= LABEL_MEDIUM_THRESHOLD:
        return score, "MEDIUM"
    return score, "LOW"


def compute_v2_tornado_confidence(
    tornado_count: int,
    wind_count: int,
    has_warning: bool,
    motion_consistency: float,
    inlier_fraction: float,
) -> Tuple[float, str]:
    """
    Confidence strength for a tornado corridor (Corridor Engine v2).

    Combines report counts with track-quality metrics so a corridor built on
    a dense, linear, warned track scores higher than one built on scattered
    reports — same inputs always produce the same score.
    """
    score = 0.0
    score += min(tornado_count * W_TORNADO_REPORT, CAP_TORNADO_REPORTS)
    score += min(wind_count * W_WIND_REPORT, CAP_WIND_REPORTS)

    if has_warning:
        score += W_ACTIVE_WARNING

    if motion_consistency >= CONSISTENCY_HIGH:
        score += W_CONSISTENCY_HIGH
    elif motion_consistency >= CONSISTENCY_MED:
        score += W_CONSISTENCY_MED
    elif motion_consistency >= CONSISTENCY_LOW:
        score += W_CONSISTENCY_LOW

    if inlier_fraction >= INLIER_HIGH:
        score += W_INLIER_HIGH
    elif inlier_fraction >= INLIER_MED:
        score += W_INLIER_MED

    return _label(min(score, 1.0))


def compute_wind_confidence(wind_count: int, has_warning: bool) -> Tuple[float, str]:
    """Confidence strength for a wind-damage swath corridor."""
    score = min(wind_count * W_WIND_CORRIDOR_REPORT, CAP_WIND_CORRIDOR)
    if has_warning:
        score += W_WIND_CORRIDOR_WARNING
    return _label(min(score, 1.0))


def compute_severe_confidence(total_count: int, has_warning: bool) -> Tuple[float, str]:
    """Confidence strength for a mixed hail/wind severe-weather swath."""
    score = min(total_count * W_SEVERE_CORRIDOR_REPORT, CAP_SEVERE_CORRIDOR)
    if has_warning:
        score += W_SEVERE_CORRIDOR_WARNING
    return _label(min(score, 1.0))
